name: Build Artifacts for PRs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  generate-tag-names:
    runs-on: ubuntu-latest
    name: Generate Tag Names
    # Skip for the release pull requests as staging artifacts will be generated
    if: startsWith(github.event.pull_request.head.ref, 'release/') != true && startsWith(github.event.pull_request.head.ref, 'hotfix-release/') != true && github.event.pull_request.head.ref != 'main'
    outputs:
      tag_name: ${{ steps.gen_tag_names.outputs.tag_name }}
      tag_name_ut: ${{ steps.gen_tag_names.outputs.tag_name_ut }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 1

      # Replace problematic characters in branch name (like '/') with safe characters (like '.')
      - name: Generate Tag Names
        id: gen_tag_names
        run: |
          tag_name=$(echo ${{ github.head_ref }} | tr "/" .)
          echo "Tag Name: $tag_name"
          echo "tag_name=$tag_name" >> $GITHUB_OUTPUT

          tag_name_ut="ut-$tag_name"
          echo "UT Tag Name: $tag_name_ut"
          echo "tag_name_ut=$tag_name_ut" >> $GITHUB_OUTPUT
