name: Prepare for Dev Environment Deployment

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:

  generate-tag-names:
    runs-on: ubuntu-latest
    name: Generate Tag Names
    # Only merged pull requests must trigger
    if: github.event.pull_request.merged == true
    outputs:
      tag_name: ${{ steps.gen_tag_names.outputs.tag_name }}
      tag_name_ut: ${{ steps.gen_tag_names.outputs.tag_name_ut }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 1

      - name: Generate Tag Names
        id: gen_tag_names
        run: |
          tag_name="latest"
          echo "Tag Name: $tag_name"
          echo "tag_name=$tag_name" >> $GITHUB_OUTPUT

          tag_name_ut="ut-$tag_name"
          echo "UT Tag Name: $tag_name_ut"
          echo "tag_name_ut=$tag_name_ut" >> $GITHUB_OUTPUT

