name: Report Code Coverage
on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

  pull_request:
    types: ['opened', 'reopened', 'synchronize']

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v3.7.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
